Remove signal in isaac sim to prevent conflict with ray tune
Error message:

      File "/isaac-sim/kit/python/lib/python3.10/site-packages/ray/tune/trainable/trainable.py", line 334, in train
        raise skipped from exception_cause(skipped)
      File "/isaac-sim/kit/python/lib/python3.10/site-packages/ray/air/_internal/util.py", line 88, in run
        self._ret = self._target(*self._args, **self._kwargs)
      File "/isaac-sim/kit/python/lib/python3.10/site-packages/ray/tune/trainable/function_trainable.py", line 53, in <lambda>
        training_func=lambda: self._trainable_func(self.config),
      File "/isaac-sim/kit/python/lib/python3.10/site-packages/ray/tune/trainable/function_trainable.py", line 261, in _trainable_func
        output = fn()
      File "/workspace/skrl-FlowQ/tune_ant_ebflow_johnson_test.py", line 43, in trainer
        _train(cfg)
      File "/workspace/skrl-FlowQ/torch_ant_ebflow_off.py", line 89, in _train
        env = load_omniverse_isaacgym_env(task_name="Ant", headless=True, num_envs=cfg['num_envs'])
      File "/workspace/skrl-FlowQ/skrl/envs/loaders/torch/omniverse_isaacgym_envs.py", line 267, in load_omniverse_isaacgym_env
        env = _OmniIsaacGymVecEnv(headless=config.headless,
      File "/isaac-sim/exts/omni.isaac.gym/omni/isaac/gym/vec_env/vec_env_base.py", line 73, in __init__
        signal.signal(signal.SIGINT, self.signal_handler)
      File "/isaac-sim/kit/python/lib/python3.10/signal.py", line 56, in signal
        handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
    ValueError: signal only works in main thread of the main interpreter